{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.admin.username | quote }}
  password: {{ .Values.admin.password | quote }}
{{- end }}
