apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.gateway.type }}
  ports:
    - port: {{ .Values.service.gateway.port }}
      targetPort: gateway
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: admin
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
