apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.gateway.type }}
  ports:
    - name: gateway
      port: {{ .Values.service.gateway.port }}
      targetPort: gateway
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    app: {{ .Release.Name }}
  {{- if and .Values.metrics.enabled .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml .Values.metrics.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - name: admin
      port: {{ .Values.service.admin.port }}
      targetPort: admin
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
